api: fix src::dest file adding when not a binary

diff --git a/geninit b/geninit
--- a/geninit
+++ b/geninit
@@ -254,8 +254,8 @@ __build_image() { # {{{
   for file in "${files[@]}"; do
     local src=${file%%::*}
     local dest=${file##*::}
-    [[ "$dest" ]] || dest=$src
-    add_binary "$src" "$dest" || { (( ++errors)); error "File not found: $file"; }
+    [[ $dest ]] || dest=$src
+    add_binary "$src" "$dest" || { (( ++errors )); error "File not found: $file"; }
   done
 
   # parse builder array
